ALTER TABLE dbo.NewComersArrivals
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_NewComersArrivals PRIMARY KEY CLUSTERED

ALTER TABLE NEWAFRAAD.dbo.followersolider DROP CONSTRAINT PK_followersolider;

ALTER TABLE dbo.followersolider
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_followersolider PRIMARY KEY CLUSTERED

ALTER TABLE NEWAFRAAD.dbo.Followerrateb DROP CONSTRAINT PK_Followerrateb;

ALTER TABLE dbo.Followerrateb
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_Followerrateb PRIMARY KEY CLUSTERED

ALTER TABLE dbo.SituationStates
   ADD SituationID INT IDENTITY
       CONSTRAINT PK_SituationStates PRIMARY KEY CLUSTERED

ALTER TABLE NEWAFRAAD.dbo.[security] DROP CONSTRAINT PK_security;

ALTER TABLE NewAFRAAD.dbo.Recommendations DROP CONSTRAINT PK_Recommendations;

ALTER TABLE dbo.Recommendations
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_Recommendations PRIMARY KEY CLUSTERED
ALTER TABLE NewAFRAAD.dbo.Recommendations ALTER COLUMN ID nvarchar(13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE NewAFRAAD.dbo.Recommendations ADD RecuStage varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Recommendations ALTER COLUMN RecuStage varchar(100) COLLATE Arabic_CI_AI NULL;


ALTER TABLE NEWAFRAAD.dbo.[security] DROP CONSTRAINT PK_security;

ALTER TABLE dbo.security
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_security PRIMARY KEY CLUSTERED

ALTER TABLE dbo.shakawi
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_shakawi PRIMARY KEY CLUSTERED

ALTER TABLE NEWAFRAAD.dbo.TravalTable DROP CONSTRAINT PK_TravalTable;

ALTER TABLE dbo.TravalTable
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_TravalTable PRIMARY KEY CLUSTERED

ALTER TABLE NEWAFRAAD.dbo.Situations DROP CONSTRAINT PK_Situations_1;

ALTER TABLE dbo.Situations
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_Situations PRIMARY KEY CLUSTERED

ALTER TABLE dbo.Brothers
   ADD ID_KEY INT IDENTITY
       CONSTRAINT PK_Brothers PRIMARY KEY CLUSTERED